name: github action for caas

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: "Github Action for CAAS"
      uses: bugstone/caas-github-action@main
      with:
        caas-secret-key: ${{secrets.CAAS_API_KEY}}
